services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - default_network
    volumes:
      - aulas:/var/lib/data

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: always
    env_file: ".env"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "10000:80"
    depends_on:
      - postgres
    networks:
      - default_network

networks:
  default_network:

volumes:
  aulas: